version: '3'

services:
  db_project:
    hostname: db_project
    image: postgres:12-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - config/.envfile
    ports:
      - "5432:5432"
    container_name: db_project

  web:
    build: .
    command: gunicorn yandex_web.wsgi:application -w 5 -b 0.0.0.0:8050
    volumes:
      - .:/code
    ports:
      - "8050:8050"
    depends_on:
      - db_project
    container_name: web